// Testbench for conv3x3.
//
// Reads sim/input.hex, sim/kernel.hex, and sim/expected.hex (generated by
// python/codegen/gen_test_vectors.py), drives the DUT for every output
// position, compares RTL results against the golden expected values, and
// writes sim/rtl_output.hex.
//
// Parameters IMG_H and IMG_W must match the --height and --width values
// used when calling gen_test_vectors.py (defaults: 8x8).
//
// How to run: see sim/run_sim.sh (Icarus Verilog).

`timescale 1ns / 1ps

module conv_tb;

    // -----------------------------------------------------------------------
    // Parameters: update these to match gen_test_vectors.py invocation.
    // -----------------------------------------------------------------------
    parameter IMG_H = 8;
    parameter IMG_W = 8;

    localparam OUT_H = IMG_H - 2;
    localparam OUT_W = IMG_W - 2;

    // -----------------------------------------------------------------------
    // DUT signals
    // -----------------------------------------------------------------------
    reg        clk;
    reg        rst_n;
    reg        start;
    reg [71:0] pixels_flat;
    reg [71:0] weights_flat;

    wire [7:0] result;
    wire       valid;

    // -----------------------------------------------------------------------
    // DUT instantiation
    // -----------------------------------------------------------------------
    conv3x3 dut (
        .clk    (clk),
        .rst_n  (rst_n),
        .start  (start),
        .pixels (pixels_flat),
        .weights(weights_flat),
        .result (result),
        .valid  (valid)
    );

    // -----------------------------------------------------------------------
    // Clock: 10 ns period (100 MHz)
    // -----------------------------------------------------------------------
    initial clk = 1'b0;
    always  #5 clk = ~clk;

    // -----------------------------------------------------------------------
    // Memory arrays for test vectors
    // -----------------------------------------------------------------------
    reg signed [7:0] image    [0 : IMG_H*IMG_W - 1];
    reg signed [7:0] kernel_w [0 : 8];
    reg signed [7:0] expected [0 : OUT_H*OUT_W - 1];
    reg        [7:0] rtl_out  [0 : OUT_H*OUT_W - 1];

    // -----------------------------------------------------------------------
    // Simulation
    // -----------------------------------------------------------------------
    integer r, c, idx;
    integer pass_count, fail_count;
    integer fd;

    initial begin
        // --- Load test vectors ---
        $readmemh("sim/input.hex",    image);
        $readmemh("sim/kernel.hex",   kernel_w);
        $readmemh("sim/expected.hex", expected);

        // --- Reset sequence ---
        rst_n = 1'b0;
        start = 1'b0;
        pixels_flat  = 72'b0;
        weights_flat = 72'b0;
        repeat (2) @(posedge clk);
        #1 rst_n = 1'b1;

        pass_count = 0;
        fail_count = 0;

        // --- Pack kernel into flat bus (constant across all output pixels) ---
        weights_flat = {
            kernel_w[0], kernel_w[1], kernel_w[2],
            kernel_w[3], kernel_w[4], kernel_w[5],
            kernel_w[6], kernel_w[7], kernel_w[8]
        };

        // --- Iterate over every output pixel position ---
        for (r = 0; r < OUT_H; r = r + 1) begin
            for (c = 0; c < OUT_W; c = c + 1) begin

                // Extract the 3x3 patch at (r, c) from the image array
                pixels_flat = {
                    image[(r+0)*IMG_W + (c+0)],
                    image[(r+0)*IMG_W + (c+1)],
                    image[(r+0)*IMG_W + (c+2)],
                    image[(r+1)*IMG_W + (c+0)],
                    image[(r+1)*IMG_W + (c+1)],
                    image[(r+1)*IMG_W + (c+2)],
                    image[(r+2)*IMG_W + (c+0)],
                    image[(r+2)*IMG_W + (c+1)],
                    image[(r+2)*IMG_W + (c+2)]
                };

                // Assert start for one cycle
                start = 1'b1;
                @(posedge clk);     // DUT registers result at this edge
                #1;
                start = 1'b0;

                // valid mirrors start with one cycle latency —
                // it should be high right now (registered at posedge above)
                if (!valid)
                    $display("WARNING: valid not asserted at output (%0d,%0d)", r, c);

                // Capture and compare
                idx = r * OUT_W + c;
                rtl_out[idx] = result;

                if (result === expected[idx]) begin
                    pass_count = pass_count + 1;
                end else begin
                    $display("MISMATCH (%0d,%0d): RTL=%4d  expected=%4d",
                             r, c,
                             $signed(result),
                             $signed(expected[idx]));
                    fail_count = fail_count + 1;
                end

            end
        end

        // --- Write rtl_output.hex ---
        fd = $fopen("sim/rtl_output.hex", "w");
        for (idx = 0; idx < OUT_H*OUT_W; idx = idx + 1) begin
            $fwrite(fd, "%h\n", rtl_out[idx]);
        end
        $fclose(fd);

        // --- Summary ---
        $display("================================================");
        $display("Image: %0dx%0d    Output: %0dx%0d", IMG_H, IMG_W, OUT_H, OUT_W);
        $display("Pass: %0d    Fail: %0d", pass_count, fail_count);
        if (fail_count == 0)
            $display("RESULT: ALL PASS");
        else
            $display("RESULT: FAILED (%0d mismatches)", fail_count);
        $display("================================================");

        $finish;
    end

endmodule
